---
spring:
  profiles: cloud
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri}
  profiles: test
  data:
    mongodb:
      uri: test
demo:
  baseUri: http://${eureka.instance.hostname}
